create mergify config file
fedora-infra/datagrepper pull request #253
Opened 2021-07-13 15:15 UTC by james02135

Signed-off-by: james02135 <james02135@hotmail.com>

2021-07-14 08:14 UTC, abompard requested changes

2021-07-14 08:14 UTC, abompard commented on .mergify.yml
> +      - "#approved-reviews-by>=1"
Same comment as in fedora-infra/datanommer#142

2021-07-20 16:06 UTC, james02135 commented
Modified the mergify config file to match the unit test names

2021-07-20 16:13 UTC, abompard approved these changes

2021-07-20 16:13 UTC, merged